#ifndef GAME_INFO_H
#define GAME_INFO_H

enum TYPE
  {
    NA, BUG, DRAGON, ELECTRIC, FIGHT, FIRE,
    FLYING, GHOST, GRASS, GROUND, ICE,
    NORMAL, POISON, PSYCHIC, ROCK, WATER
  };

enum CONDITION
{
  NO_CONDITION, BURNED, FROZEN, PARALYZED, POISONED,
  ASLEEP, CONFUSED, ATTRACTED, CURSED
};

#endif
